Repository masterchef2209/GETSETFOSSCodingTasks, pull requests merged in 2019-11, with the labels that each got.

#59 Add files via upload
  Screenshot (1).png
Labels: Very Easy, getsetfoss2019

#58 Add files via upload
  Screenshot (29).png
Labels: Very Easy, getsetfoss2019

#57 solution weapon value(SC31)
  Capture.PNG
  hardques.PNG
Labels: Easy, getsetfoss2019

#52 solution for weapon value
  screenshots_of_accepted_solution/Screenshot (21).png
Labels: Very Easy, getsetfoss2019

#51 Pigmeister
  screenshots_of_accepted_solution/PHCUL.PNG
  screenshots_of_accepted_solution/paintingbox.PNG
Labels: Medium, getsetfoss2019

#53 Ishansharma
  screenshots_of_accepted_solution/hardsequence.PNG
  screenshots_of_accepted_solution/paintingboxes.PNG
  screenshots_of_accepted_solution/weaponvalue.PNG
Labels: Extra, getsetfoss2019

#64 solution of SC31
  sc31.png
Labels: Very Easy, getsetfoss2019

#62 SC31
  hrdseq.png
  weapon value.png
Labels: Easy, getsetfoss2019

#61 Solution for painting boxes
  Painting Boxes.PNG
Labels: Extra, getsetfoss2019

#48 Siddham
  hard sequence.PNG
  weapons.PNG
Labels: Easy, getsetfoss2019

#65 i have solve this question weapon value(Sc31)
  weapon value.PNG
Labels: Very Easy, getsetfoss2019

#66 answers of problem weapons and hardsequence
  screenshots_of_accepted_solution/hard sequence.PNG
  screenshots_of_accepted_solution/weapons.PNG
Labels: Easy, getsetfoss2019

#67 I have solved this problem "Hard Sequencce " (HRDSEQ)
  hard squence.png
Labels: Very Easy, getsetfoss2019

#63 Add files via upload
  hrdseq033.png
Labels: Very Easy, good first issue

#69 codechef nov long challenge SC31
  screenshots_of_accepted_solution/SC31.PNG
Labels: Very Easy, getsetfoss2019

#71 Kop1
  snipped hard sequence.PNG
  snipped sc31.PNG
Labels: Easy, getsetfoss2019

#81 Code chef SC31,HRDSEQ RESUBMISSION
  screenshots_of_accepted_solution/Screenshot from 2019-11-05 01-15-53.png
  screenshots_of_accepted_solution/Screenshot from 2019-11-05 01-16-13.png
Labels: Easy, getsetfoss2019

#78 hackerrank painting boxes
  screenshots_of_accepted_solution/paintbox.PNG
Labels: Extra, getsetfoss2019

#80 solution to painting boxes
  box.PNG
Labels: Extra, getsetfoss2019

#77 Hackerrank Painting Boxes
  screenshots_of_accepted_solution/Painting Boxes.PNG
Labels: Extra, getsetfoss2019

#83 Issue #1 Weapon Value
  screenshots_of_accepted_solution/Weapon Value.png
Labels: Very Easy, getsetfoss2019

#82 Issue #2 Hard Sequence
  screenshots_of_accepted_solution/Hard Sequence.png
Labels: Very Easy, getsetfoss2019

#74 code chef november long weapon value
  Capture d.PNG
  screenshots_of_accepted_solution/Capture.PNG
Labels: Easy, getsetfoss2019

#92 Issue#70 Codeforces Round#598 Div 3 Participation
  screenshots_of_accepted_solution/codeforces.PNG
Labels: Extra, getsetfoss2019

#86 UPDATE hard sequence HRDSEQ
  Screenshot (11).png
  Screenshot (12).png
Labels: Very Easy, getsetfoss2019

#109 i solved this issue.
  screenshots_of_accepted_solution/sc31.PNG
Labels: Very Easy, getsetfoss2019

#89 codechef long weapon value (SC31)
  screenshots_of_accepted_solution/weapon value.JPG
Labels: Very Easy, getsetfoss2019

#116 codeforces #598 div 3
  Screenshot (30).png
Labels: Extra, getsetfoss2019

#115 Participation in codeforces div 3
  Codeforces_contest
Labels: Extra, getsetfoss2019

#117 #598 div3
  Screenshot from 2019-11-05 21-16-24.png
Labels: Extra, getsetfoss2019

#113 I participated this contest #598
  participation.png
Labels: Extra, getsetfoss2019

#104 Participation in codeforces and solved 1 problem.
  bYHk8Wuehw.png
Labels: Extra, getsetfoss2019

#96 Issue #84 CodeForces 598 Div 3 Participation
  screenshots_of_accepted_solution/Capture.PNG
Labels: Extra, getsetfoss2019

#110 Participation in div3 #598
  Screenshot (190).png
Labels: Extra, getsetfoss2019

#93 Payment Without Change solution
  code.png
Labels: Extra, getsetfoss2019

#79 codeforces contest rank-4669
  codeforces.PNG
Labels: Medium, getsetfoss2019

#131 November Long Contest(HRDSEQ)
  Screenshot (89).png
  screenshots_of_accepted_solution/Screenshot (93).png
Labels: Very Easy, getsetfoss2019

#148 Add screenshot for weapon value
  screenshots_of_accepted_solution/Screenshot (94).png
Labels: Very Easy, getsetfoss2019

#151 Add screenshot for painting boxes
  Screenshot (91).png
Labels: Easy, getsetfoss2019

#156 codeforces_rank
  codeforces_contest_rank.png
Labels: Medium, getsetfoss2019

#122 codeforces challenge
  Screenshot from 2019-11-05 18-33-38.png
Labels: Extra, getsetfoss2019

#124 issue #84 6.4 rank in Codeforces Div3 #598
  Retarded-Ape.png
Labels: Extra, getsetfoss2019

#123 participation
  Screenshot (4).png
Labels: Extra, getsetfoss2019

#153 hard sequence
  Annotation 2019-11-06 013935.png
Labels: For everyone, Very Easy, getsetfoss2019

#152 Nirbhay singh
  Screenshot (25).png
Labels: For everyone, Very Easy, getsetfoss2019

#150 participation in codeforces div 3(#598)
  Annotation 2019-11-05 233728.png
  Screenshot (21).png
Labels: Extra, getsetfoss2019

#154 painting boxes
  Screenshot (31).png
Labels: Extra, getsetfoss2019

#161 Diwali
  Screenshot from 2019-11-06 14-47-14.png
Labels: Medium, getsetfoss2019

#97 Weaponvalue
  screenshots_of_accepted_solution/weapn value.PNG
Labels: Very Easy, getsetfoss2019

#99 solution for weapon value
  Screenshot from 2019-11-05 18-53-11.png
Labels: Very Easy, getsetfoss2019

#101 Add files via upload
  Screenshot (32).png
Labels: Very Easy, getsetfoss2019

#102 Hard Sequence
  Screenshot from 2019-11-05 19-23-31.png
Labels: Very Easy, getsetfoss2019

#107 I have solved this problem
  screenshots_of_accepted_solution/hrdseq.PNG
Labels: Very Easy, getsetfoss2019

#108 hard sequence
  Screenshot (28).png
Labels: Very Easy, getsetfoss2019

#112 solution of november challenge
  weapon.png
Labels: Very Easy, getsetfoss2019

#114 Hrdseq soln
  Hard Sequence (HRDSEQ)
  Screenshot (204).png
Labels: Very Easy, getsetfoss2019

#118 codechef long hard sequence(HRDSEQ)
  screenshots_of_accepted_solution/hard sequence.JPG
Labels: Very Easy, getsetfoss2019

#128 codechef long weapon value(SC31)
  screenshots_of_accepted_solution/SC31.png
Labels: Very Easy, getsetfoss2019

#126 Add Solution -SC31(Mohit Agarwal)
  screenshots_of_accepted_solution/Mohit_SOlution_SC31.png
Labels: Very Easy, getsetfoss2019

#121 Hard sequence
  Screenshot (3).png
Labels: Very Easy, getsetfoss2019

#169 Solution to painting boxes
  H6y4KFR9HE.png
Labels: Extra, getsetfoss2019

#166 codechef long physical exercise (PHCUL)
  screenshots_of_accepted_solution/physical exercise.JPG
Labels: Easy, getsetfoss2019

#165 diwali sweeets completed
  Screenshot (26).png
Labels: Extra, getsetfoss2019

#164 Mohit Agarwal(diwali sweets)
  Diwali Sweets  Easy Version  Submission.png
Labels: Extra, getsetfoss2019

#162 diwali sweet
  Screenshot from 2019-11-06 15-50-29.png
Labels: Extra, getsetfoss2019

#160 hackerrank question painting box
  screenshots_of_accepted_solution/Capture 3.PNG
Labels: Extra, getsetfoss2019

#159 Mohit agarwal(painting boxes)
  solution_painting_boxes.png
Labels: Extra, getsetfoss2019

#170 painting box solution
  Screenshot (27).png
Labels: Extra, getsetfoss2019

#149 Physical exercise
  hard sequence.PNG
  physical exercise.PNG
  weapon value.PNG
Labels: Easy, Extra, getsetfoss2019

#145 Add files via upload
  Screenshot (9).png
Labels: Very Easy, getsetfoss2019

#129 codechef long hard sequence(HRDSEQ)
  screenshots_of_accepted_solution/HRDSEQ.png
Labels: Very Easy, getsetfoss2019

#141 codechef long weapon value(SC31)
  screenshots_of_accepted_solution/weapon value.png
Labels: Very Easy, getsetfoss2019

#139 I have solved this question "paint box"
  paint box.png
Labels: Extra, getsetfoss2019

#144 hrdseq
  Screenshot (2).png
Labels: Very Easy, getsetfoss2019

#143 codechef long hard sequence(HRDSEQ)
  screenshots_of_accepted_solution/hard sequence.png
Labels: Very Easy, getsetfoss2019

#140 i solved sc31
  screenshots_of_accepted_solution/sc31.PNG
Labels: Very Easy, getsetfoss2019

#137 i solved this problem
  screenshots_of_accepted_solution/painting box.PNG
Labels: Extra, getsetfoss2019

#136 Solution to Weapon Value
  Wepval.PNG
  hrdseq.PNG
Labels: Easy, getsetfoss2019

#135 screenshot of verified solution
  painting boxes.PNG
Labels: Extra, getsetfoss2019

#171 Issue#168 Codeforces #599 div2 Participation
  screenshots_of_accepted_solution/codeforces#599.PNG
Labels: Extra, getsetfoss2019

#133 Weapon value
  screenshots_of_accepted_solution/Hard sequense.PNG
  screenshots_of_accepted_solution/Weapon value.png
Labels: Easy, getsetfoss2019

#105 Painting box
  painting box.PNG
Labels: Extra, getsetfoss2019

#179 codeforces round #598 (DIV3)
  Screenshot (1).png
Labels: Medium, getsetfoss2019

#182 participated in codeforces div2
  chrome_5GCrjO0d6W.png
Labels: Extra, getsetfoss2019

#181 hackerrank painting boxes
  screenshots_of_accepted_solution/painting boxes.PNG
Labels: Extra, getsetfoss2019

#174 participated in codeforces : (DIV.2)
  Screenshot (39).png
Labels: Extra, getsetfoss2019

#176 painting boxes
  Annotation 2019-11-07 022446.png
Labels: Extra, getsetfoss2019

#183 codeforces div2 #599 issue#157
  codeforces7.PNG
Labels: Medium, getsetfoss2019

#185 Add screenshot for hard sequence.
  screenshots_of_accepted_solution/Screenshot (3).png
Labels: Very Easy, getsetfoss2019

#189 Screenshot of participation #168
  screenshots_of_accepted_solution/Screenshot of participation in div2 #599.png
Labels: Extra, getsetfoss2019

#187 Kkrr
  participation2.png
Labels: Extra, getsetfoss2019

#194 Adding diwali sweets
  div3.png
  diwali sweets.png
Labels: Extra, getsetfoss2019

#193 hackerrank_painting_box
  paintingbox.PNG
Labels: Extra, getsetfoss2019

#191 physical exercise accepted
  screenshots_of_accepted_solution/pesc.PNG
Labels: Easy, getsetfoss2019

#190 Add files via upload
  screenshots_of_accepted_solution/nov long q1.PNG
Labels: Very Easy, getsetfoss2019

#195 Add files via upload
  paiting box.PNG
Labels: Extra, getsetfoss2019

#198 hackerrank painting boxes
  screenshots_of_accepted_solution/ayush paint.png
Labels: Extra, getsetfoss2019

#197 Solution to painting boxes
  paintingboxes.png
Labels: Extra, getsetfoss2019

#196 physical exercise issue#3
  codechef.PNG
Labels: Extra, getsetfoss2019

#201 DIV 2 #599 Participation
  codeforces.png
Labels: Extra, getsetfoss2019

#204 Codechef Nov Long Challenge PHCUL
  screenshots_of_accepted_solution/Physical Exercise.png
Labels: Easy, getsetfoss2019

#203 participation proof ARC
  ARC.PNG
Labels: Extra, getsetfoss2019

#205 atcoder contest
  Annotation 2019-11-09 205009.png
Labels: Medium, getsetfoss2019

#202 Issue #200
  Screenshot (44).png
Labels: Extra, getsetfoss2019

#208 ARC issue#200
  atcoder.PNG
Labels: Extra, getsetfoss2019

#210 Atcoder
  Screenshot from 2019-11-10 01-48-32.png
Labels: Extra, getsetfoss2019

#209 solved issue #200,user name:KOP1
  Screenshot (49).png
Labels: Extra, getsetfoss2019

#211 Issue#200 ARC Participation
  screenshots_of_accepted_solution/atcoder.PNG
Labels: Extra, getsetfoss2019

#213 I have participated in this contest.
  part3.png
Labels: Extra, getsetfoss2019

#214 codechef november long challenge - Physical exercise(PHCUL)
  PHCUL.png
Labels: Easy, getsetfoss2019

#215 Kkk
  diwali sweets.PNG
Labels: Extra, getsetfoss2019

#216 Issue#155 Diwali Sweets
  screenshots_of_accepted_solution/diwalisweets.PNG
Labels: Extra, getsetfoss2019

#218 Issue#217 Candy Business
  screenshots_of_accepted_solution/candy.PNG
Labels: Hard, getsetfoss2019

#219 solved diwali sweets
  chrome_NFM4LSNI4h.png
Labels: Extra, getsetfoss2019

#220 hackerrank candy buisness
  screenshots_of_accepted_solution/candy_buisness_yug.JPG
Labels: Extra, getsetfoss2019

#221 solved issue#3,PHCUL
  chrome_VhnrDVr79q.png
Labels: Easy, getsetfoss2019

#225 hacker rank - candy business
  candy business.png
Labels: Extra, getsetfoss2019

#229 hackerrank diwali sweets
  screenshots_of_accepted_solution/Diwali_swets.JPG
Labels: Extra, getsetfoss2019

#228 hacker rank - Diwali sweets
  Diwali sweets.png
Labels: Extra, getsetfoss2019

#230 diwali sweets accepted
  screenshots_of_accepted_solution/diwali sweets.PNG
Labels: Extra, getsetfoss2019

#233 Issue#224 Prime Reduction
  screenshots_of_accepted_solution/prime.PNG
Labels: Medium, getsetfoss2019

#245 Added ss of Points in a plane 2
  screenshots_of_accepted_solution/Screenshot from 2019-11-16 16-05-57.png
Labels: Easy, getsetfoss2019

#247 AtCoder Beginner Contest 145
  screenshots_of_accepted_solution/ABC_at_code.JPG
Labels: Extra, getsetfoss2019

#246 abc145Rank
  Standings - AtCoder Beginner Contest 145 main.pdf
Labels: Extra, getsetfoss2019

#249 ABC 145 rank 4146
  screenshots_of_accepted_solution/Screenshot (187).png
  screenshots_of_accepted_solution/Screenshot (201).png
Labels: Extra, getsetfoss2019

#253 Participated in Google Kickstart Round H, rank >1500
  Screenshot (284).png
Labels: Easy, getsetfoss2019

#251 Codeforces round #600 (div. 2)
  Screenshot from 2019-11-17 12-41-19.png
  Screenshot from 2019-11-17 12-49-15.png
Labels: Extra, getsetfoss2019

#254 Codeforces div2 round 600 rank 5125
  Screenshot (217).png
Labels: Extra, getsetfoss2019

#255 google kick start 2019
  screenshots_of_accepted_solution/kick_by_seeker.JPG
Labels: Extra, getsetfoss2019

#256 kickstart rank 1513
  kickstart.png
Labels: Easy, getsetfoss2019

#258 Issue #241 Participate in Google Kickstart 2019 Round H, rank<=1500
  screenshots_of_accepted_solution/Screenshot Gkickstart.png
Labels: Medium, getsetfoss2019

#257 Issue#241 Google Kickstart rank <= 1500
  screenshots_of_accepted_solution/kickstart.PNG
Labels: Medium, getsetfoss2019

#260 Issue #259 Solve Number Operations
  screenshots_of_accepted_solution/Screenshot of Number Operations.png
Labels: Medium, getsetfoss2019

#261 diwali sweets
  diwali sw.png
Labels: Extra, getsetfoss2019

#266 number operation hackerrank
  screenshots_of_accepted_solution/number_operation_yug.JPG
Labels: Extra, getsetfoss2019

#267 Issue #263 Participate in Codeforces div2 round 601 with 3000<= rank <=5000
  screenshots_of_accepted_solution/Screenshot Codeforces 601.png
Labels: Medium, getsetfoss2019

#268 Issue #5 Solve Painting Boxes
  screenshots_of_accepted_solution/Screenshot yk1ax Painting boxes.png
Labels: Extra, getsetfoss2019

#269 Add files via upload
  Screenshot (59).png
Labels: Extra, getsetfoss2019
